# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindowUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(458, 397)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabSelector = QtWidgets.QTabWidget(self.centralwidget)
        self.tabSelector.setGeometry(QtCore.QRect(20, 10, 421, 341))
        self.tabSelector.setAutoFillBackground(False)
        self.tabSelector.setStyleSheet("")
        self.tabSelector.setObjectName("tabSelector")
        self.tabSearchFiles = QtWidgets.QWidget()
        self.tabSearchFiles.setObjectName("tabSearchFiles")
        self.btnFindText = QtWidgets.QPushButton(self.tabSearchFiles)
        self.btnFindText.setGeometry(QtCore.QRect(300, 30, 91, 21))
        self.btnFindText.setObjectName("btnFindText")
        self.txtTextToFind = QtWidgets.QLineEdit(self.tabSearchFiles)
        self.txtTextToFind.setGeometry(QtCore.QRect(130, 30, 161, 20))
        self.txtTextToFind.setObjectName("txtTextToFind")
        self.label_3 = QtWidgets.QLabel(self.tabSearchFiles)
        self.label_3.setGeometry(QtCore.QRect(30, 30, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.txtFindResults = QtWidgets.QTextEdit(self.tabSearchFiles)
        self.txtFindResults.setGeometry(QtCore.QRect(30, 60, 361, 251))
        self.txtFindResults.setObjectName("txtFindResults")
        self.tabSelector.addTab(self.tabSearchFiles, "")
        self.tabDirectoryCleanup = QtWidgets.QWidget()
        self.tabDirectoryCleanup.setObjectName("tabDirectoryCleanup")
        self.btnDirectory = QtWidgets.QPushButton(self.tabDirectoryCleanup)
        self.btnDirectory.setGeometry(QtCore.QRect(300, 30, 91, 21))
        self.btnDirectory.setObjectName("btnDirectory")
        self.txtDirectory = QtWidgets.QLineEdit(self.tabDirectoryCleanup)
        self.txtDirectory.setGeometry(QtCore.QRect(130, 30, 161, 20))
        self.txtDirectory.setObjectName("txtDirectory")
        self.label_4 = QtWidgets.QLabel(self.tabDirectoryCleanup)
        self.label_4.setGeometry(QtCore.QRect(30, 30, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.txtDirectoryResults = QtWidgets.QTextEdit(self.tabDirectoryCleanup)
        self.txtDirectoryResults.setGeometry(QtCore.QRect(30, 60, 361, 251))
        self.txtDirectoryResults.setObjectName("txtDirectoryResults")
        self.tabSelector.addTab(self.tabDirectoryCleanup, "")
        self.tabServerMonitor = QtWidgets.QWidget()
        self.tabServerMonitor.setObjectName("tabServerMonitor")
        self.txtServerToMonitor = QtWidgets.QLineEdit(self.tabServerMonitor)
        self.txtServerToMonitor.setGeometry(QtCore.QRect(130, 30, 161, 20))
        self.txtServerToMonitor.setObjectName("txtServerToMonitor")
        self.label_2 = QtWidgets.QLabel(self.tabServerMonitor)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btnMonitorServer = QtWidgets.QPushButton(self.tabServerMonitor)
        self.btnMonitorServer.setGeometry(QtCore.QRect(300, 30, 91, 21))
        self.btnMonitorServer.setObjectName("btnMonitorServer")
        self.txtServerMonitorResults = QtWidgets.QTextEdit(self.tabServerMonitor)
        self.txtServerMonitorResults.setGeometry(QtCore.QRect(30, 60, 361, 251))
        self.txtServerMonitorResults.setObjectName("txtServerMonitorResults")
        self.tabSelector.addTab(self.tabServerMonitor, "")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(390, 10, 47, 13))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 458, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        mainWindow.setMenuBar(self.menubar)
        self.actionSave_Configuration = QtWidgets.QAction(mainWindow)
        self.actionSave_Configuration.setCheckable(False)
        self.actionSave_Configuration.setChecked(False)
        self.actionSave_Configuration.setObjectName("actionSave_Configuration")
        self.actionExit = QtWidgets.QAction(mainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionView_Current_Users_0_online = QtWidgets.QAction(mainWindow)
        self.actionView_Current_Users_0_online.setObjectName("actionView_Current_Users_0_online")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(mainWindow)
        self.tabSelector.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "SHU Network Management Suite"))
        self.btnFindText.setText(_translate("mainWindow", "Search Files"))
        self.label_3.setText(_translate("mainWindow", "Text To Find"))
        self.tabSelector.setTabText(self.tabSelector.indexOf(self.tabSearchFiles), _translate("mainWindow", "Search Files"))
        self.btnDirectory.setText(_translate("mainWindow", "Clean Directory"))
        self.label_4.setText(_translate("mainWindow", "Directory Loc."))
        self.tabSelector.setTabText(self.tabSelector.indexOf(self.tabDirectoryCleanup), _translate("mainWindow", "Directory Cleanup"))
        self.label_2.setText(_translate("mainWindow", "Server Address"))
        self.btnMonitorServer.setText(_translate("mainWindow", "Monitor Server"))
        self.tabSelector.setTabText(self.tabSelector.indexOf(self.tabServerMonitor), _translate("mainWindow", "Server Monitor"))
        self.label.setText(_translate("mainWindow", "00:00"))
        self.menuFile.setTitle(_translate("mainWindow", "File"))
        self.menuHelp.setTitle(_translate("mainWindow", "Help"))
        self.actionSave_Configuration.setText(_translate("mainWindow", "Save Configuration"))
        self.actionExit.setText(_translate("mainWindow", "Exit"))
        self.actionView_Current_Users_0_online.setText(_translate("mainWindow", "View Current Users (0 online)"))

